export { validateProjectName } from "./projectValidation.ts";
export { createFolderStructure } from "./createFolderStructure.ts";
export { installDependencies } from "./installDependencies.ts";
export { setupTailwind } from "./setupTailwind.ts";
export { setupAxios } from "./setupAxios.ts";
export { setupShadcn } from "./setupShadcn.ts";
export { setupVitest } from "./setupVitest.ts";
export { checkForUpdates } from "./checkForUpdates.ts";
export { installVite } from "./installVite.ts";
