export { validateProjectName } from "./projectValidation.js";
export { createFolderStructure } from "./createFolderStructure.js";
export { installDependencies } from "./installDependencies.js";
export { setupTailwind } from "./setupTailwind.js";
export { setupAxios } from "./setupAxios.js";
export { setupShadcn } from "./setupShadcn.js";
export { setupVitest } from "./setupVitest.js";
export { checkForUpdates } from "./checkForUpdates.js";
export { installVite } from "./installVite.js";
