name: Biome CI

on:
  pull_request:
    branches:
      - main

jobs:
  lint-format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Biome Lint, Format, and Check
        run: |
          npm run biome:lint
          npm run biome:format
          npm run biome:check
